// eslint-disable-next-line filenames/match-exported
import { routing } from "@/i18n/routing";
import "./globals.css";
import { jaJP } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Open_Sans } from "next/font/google";
import { notFound } from "next/navigation";
import Layout from "./_components/Layout";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Rexto Studio",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>): Promise<React.JSX.Element> {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <ClerkProvider localization={locale === "ja" ? jaJP : undefined}>
      <html lang={locale}>
        <body className={openSans.className}>
          <NextIntlClientProvider>
            <Layout>{children}</Layout>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
